[2024-01-07 18:26:46,868] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables manual__2024-01-07T18:26:30.367704+00:00 [queued]>
[2024-01-07 18:26:46,883] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables manual__2024-01-07T18:26:30.367704+00:00 [queued]>
[2024-01-07 18:26:46,883] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-01-07 18:26:46,883] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2024-01-07 18:26:46,883] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-01-07 18:26:46,909] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): encoding_categorical_variables> on 2024-01-07 18:26:30.367704+00:00
[2024-01-07 18:26:46,917] {standard_task_runner.py:52} INFO - Started process 4850 to run task
[2024-01-07 18:26:46,920] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_scoring_training_pipeline', 'encoding_categorical_variables', 'manual__2024-01-07T18:26:30.367704+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/lead_scoring_training_pipeline/lead_scoring_training_pipeline.py', '--cfg-path', '/tmp/tmp0w47dtaa', '--error-file', '/tmp/tmpz2p3vpeq']
[2024-01-07 18:26:46,920] {standard_task_runner.py:80} INFO - Job 30: Subtask encoding_categorical_variables
[2024-01-07 18:26:47,002] {task_command.py:371} INFO - Running <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables manual__2024-01-07T18:26:30.367704+00:00 [running]> on host a3830b6d5f93
[2024-01-07 18:26:47,088] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_scoring_training_pipeline
AIRFLOW_CTX_TASK_ID=encoding_categorical_variables
AIRFLOW_CTX_EXECUTION_DATE=2024-01-07T18:26:30.367704+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-07T18:26:30.367704+00:00
[2024-01-07 18:26:47,088] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/dags/lead_scoring_training_pipeline/utils.py", line 58, in encode_features
    cnx = sqlite3.connect(DB_PATH + DB_FILE_NAME)
sqlite3.OperationalError: unable to open database file
[2024-01-07 18:26:47,100] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=Lead_scoring_training_pipeline, task_id=encoding_categorical_variables, execution_date=20240107T182630, start_date=20240107T182646, end_date=20240107T182647
[2024-01-07 18:26:47,125] {standard_task_runner.py:92} ERROR - Failed to execute job 30 for task encoding_categorical_variables (unable to open database file; 4850)
[2024-01-07 18:26:47,172] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-07 18:26:47,236] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
